# Generated by Django 6.0.6 on 2026-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facture',
            new_name='factures_abonne__d698c8_idx',
            old_name='factures_abonne_id_idx',
        ),
        migrations.RenameIndex(
            model_name='facture',
            new_name='factures_campagn_a14a28_idx',
            old_name='factures_campagne_id_idx',
        ),
        migrations.RenameIndex(
            model_name='facture',
            new_name='factures_statut_d839a2_idx',
            old_name='factures_statut_idx',
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_mobile_money',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
