# Generated by Django 5.2.15 on 2026-07-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_numero_mobile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='pdf_template_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
