# Generated by Django 5.2.15 on 2026-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_pdf_template_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='facture',
            name='nature',
            field=models.CharField(choices=[('CONSOMMATION', 'Consommation relevée'), ('REGULARISATION', "Régularisation d'arriéré")], default='CONSOMMATION', max_length=16),
        ),
        migrations.AlterField(
            model_name='facture',
            name='campagne_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
