# Generated by Django 5.2.15 on 2026-08-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_facture_motif_facture_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='annulee_par',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='motif_annulation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='facture',
            name='remplace_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='facture',
            name='remplacee_par_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('IMPAYEE', 'Impayée'), ('PARTIELLE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='IMPAYEE', max_length=10),
        ),
    ]
