# Generated by Django 5.2.15 on 2026-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_facture_annulee_par_facture_date_annulation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['-date_generation'], name='factures_date_ge_1bed83_idx'),
        ),
    ]
