# Generated by Django 5.2.17 on 2026-09-04 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_audit_log_immutable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_evenement', models.CharField(choices=[('FACTURE_GENEREE', 'Facture générée')], max_length=50)),
                ('payload', models.JSONField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec définitif')], default='EN_ATTENTE', max_length=10)),
                ('tentatives', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envoye_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['statut'], name='outbox_even_statut_f342eb_idx')],
            },
        ),
    ]
