# Generated by Django 5.2.16 on 2026-09-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_audit_log_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
