# Generated by Django 5.2.17 on 2026-09-08
#
# Migration de SCHÉMA uniquement : bascule `email`/`phone_number` vers le
# champ chiffré (comptes/fields.py::EncryptedCharField) et élargit leurs
# colonnes en TEXT (un token Fernet dépasse largement VARCHAR(255)/VARCHAR(20)
# — voir EncryptedCharField.db_type). Elle NE rechiffre PAS les lignes
# existantes : c'est le rôle de la migration de données suivante
# (0012_encrypt_existing_email_phone_data), qui doit impérativement s'exécuter
# APRÈS celle-ci (colonnes déjà élargies) mais raisonne en SQL brut pour ne
# pas repasser par ces mêmes champs déjà « chiffrants » à cette étape — même
# patron que services/notification/notifications/migrations/
# 0007_encrypt_telephone_field.py / 0008_encrypt_existing_telephone_data.py.
#
# `unique=True` est retiré des deux champs ici (il migre vers les colonnes de
# hash `email_hash`/`phone_number_hash`, ajoutées ci-dessous) : Fernet est un
# chiffrement non déterministe, une contrainte d'unicité sur le champ chiffré
# lui-même ne protégerait plus rien (voir comptes/fields.py, tête de module).
#
# `email_hash`/`phone_number_hash` sont ajoutés ICI en `null=True` et SANS
# `unique=True` — délibérément, pour ne pas violer de contrainte tant que la
# migration de données suivante n'a pas rempli ces colonnes pour les lignes
# existantes. `unique=True` (et `null=False` pour `phone_number_hash`, qui ne
# doit jamais rester vide) n'est posé qu'en
# 0013_alter_email_phone_hash_unique, une fois les données backfillées — même
# stratégie en trois temps que celle déjà appliquée à `phone_number` lui-même
# entre 0003_user_phone_number_phoneotptoken (ajouté nullable) et
# 0005_alter_user_phone_number (durci en non-nullable).

import comptes.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_audit_log_role_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=comptes.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=comptes.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
