# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import campagne_service_pb2 as campagne__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in campagne_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CampagneServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCampagne = channel.unary_unary(
                '/campagne.CampagneService/CreateCampagne',
                request_serializer=campagne__service__pb2.CreateCampagneRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.CampagneResponse.FromString,
                _registered_method=True)
        self.GetCampagne = channel.unary_unary(
                '/campagne.CampagneService/GetCampagne',
                request_serializer=campagne__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.CampagneResponse.FromString,
                _registered_method=True)
        self.ListCampagnes = channel.unary_unary(
                '/campagne.CampagneService/ListCampagnes',
                request_serializer=campagne__service__pb2.ListCampagnesRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ListCampagnesResponse.FromString,
                _registered_method=True)
        self.AssignerAgent = channel.unary_unary(
                '/campagne.CampagneService/AssignerAgent',
                request_serializer=campagne__service__pb2.AssignerAgentRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.CampagneResponse.FromString,
                _registered_method=True)
        self.SaisirIndex = channel.unary_unary(
                '/campagne.CampagneService/SaisirIndex',
                request_serializer=campagne__service__pb2.SaisirIndexRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ReleveResponse.FromString,
                _registered_method=True)
        self.CorrigerReleve = channel.unary_unary(
                '/campagne.CampagneService/CorrigerReleve',
                request_serializer=campagne__service__pb2.CorrigerReleveRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ReleveResponse.FromString,
                _registered_method=True)
        self.MarquerNonReleve = channel.unary_unary(
                '/campagne.CampagneService/MarquerNonReleve',
                request_serializer=campagne__service__pb2.MarquerNonReleveRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ReleveResponse.FromString,
                _registered_method=True)
        self.GetReleve = channel.unary_unary(
                '/campagne.CampagneService/GetReleve',
                request_serializer=campagne__service__pb2.ReleveIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ReleveResponse.FromString,
                _registered_method=True)
        self.ListReleves = channel.unary_unary(
                '/campagne.CampagneService/ListReleves',
                request_serializer=campagne__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ListRelevesResponse.FromString,
                _registered_method=True)
        self.GetProgression = channel.unary_unary(
                '/campagne.CampagneService/GetProgression',
                request_serializer=campagne__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ProgressionResponse.FromString,
                _registered_method=True)
        self.GetResumeCloture = channel.unary_unary(
                '/campagne.CampagneService/GetResumeCloture',
                request_serializer=campagne__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.ResumeClotureResponse.FromString,
                _registered_method=True)
        self.CloturerCampagne = channel.unary_unary(
                '/campagne.CampagneService/CloturerCampagne',
                request_serializer=campagne__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.CampagneResponse.FromString,
                _registered_method=True)
        self.GetDernierIndex = channel.unary_unary(
                '/campagne.CampagneService/GetDernierIndex',
                request_serializer=campagne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=campagne__service__pb2.DernierIndexResponse.FromString,
                _registered_method=True)


class CampagneServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateCampagne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCampagne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCampagnes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignerAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaisirIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CorrigerReleve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarquerNonReleve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReleve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReleves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgression(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResumeCloture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloturerCampagne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDernierIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CampagneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCampagne,
                    request_deserializer=campagne__service__pb2.CreateCampagneRequest.FromString,
                    response_serializer=campagne__service__pb2.CampagneResponse.SerializeToString,
            ),
            'GetCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCampagne,
                    request_deserializer=campagne__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=campagne__service__pb2.CampagneResponse.SerializeToString,
            ),
            'ListCampagnes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCampagnes,
                    request_deserializer=campagne__service__pb2.ListCampagnesRequest.FromString,
                    response_serializer=campagne__service__pb2.ListCampagnesResponse.SerializeToString,
            ),
            'AssignerAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignerAgent,
                    request_deserializer=campagne__service__pb2.AssignerAgentRequest.FromString,
                    response_serializer=campagne__service__pb2.CampagneResponse.SerializeToString,
            ),
            'SaisirIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.SaisirIndex,
                    request_deserializer=campagne__service__pb2.SaisirIndexRequest.FromString,
                    response_serializer=campagne__service__pb2.ReleveResponse.SerializeToString,
            ),
            'CorrigerReleve': grpc.unary_unary_rpc_method_handler(
                    servicer.CorrigerReleve,
                    request_deserializer=campagne__service__pb2.CorrigerReleveRequest.FromString,
                    response_serializer=campagne__service__pb2.ReleveResponse.SerializeToString,
            ),
            'MarquerNonReleve': grpc.unary_unary_rpc_method_handler(
                    servicer.MarquerNonReleve,
                    request_deserializer=campagne__service__pb2.MarquerNonReleveRequest.FromString,
                    response_serializer=campagne__service__pb2.ReleveResponse.SerializeToString,
            ),
            'GetReleve': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReleve,
                    request_deserializer=campagne__service__pb2.ReleveIdRequest.FromString,
                    response_serializer=campagne__service__pb2.ReleveResponse.SerializeToString,
            ),
            'ListReleves': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReleves,
                    request_deserializer=campagne__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=campagne__service__pb2.ListRelevesResponse.SerializeToString,
            ),
            'GetProgression': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgression,
                    request_deserializer=campagne__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=campagne__service__pb2.ProgressionResponse.SerializeToString,
            ),
            'GetResumeCloture': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResumeCloture,
                    request_deserializer=campagne__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=campagne__service__pb2.ResumeClotureResponse.SerializeToString,
            ),
            'CloturerCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.CloturerCampagne,
                    request_deserializer=campagne__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=campagne__service__pb2.CampagneResponse.SerializeToString,
            ),
            'GetDernierIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDernierIndex,
                    request_deserializer=campagne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=campagne__service__pb2.DernierIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'campagne.CampagneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('campagne.CampagneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CampagneService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/CreateCampagne',
            campagne__service__pb2.CreateCampagneRequest.SerializeToString,
            campagne__service__pb2.CampagneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/GetCampagne',
            campagne__service__pb2.CampagneIdRequest.SerializeToString,
            campagne__service__pb2.CampagneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCampagnes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/ListCampagnes',
            campagne__service__pb2.ListCampagnesRequest.SerializeToString,
            campagne__service__pb2.ListCampagnesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignerAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/AssignerAgent',
            campagne__service__pb2.AssignerAgentRequest.SerializeToString,
            campagne__service__pb2.CampagneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaisirIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/SaisirIndex',
            campagne__service__pb2.SaisirIndexRequest.SerializeToString,
            campagne__service__pb2.ReleveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CorrigerReleve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/CorrigerReleve',
            campagne__service__pb2.CorrigerReleveRequest.SerializeToString,
            campagne__service__pb2.ReleveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarquerNonReleve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/MarquerNonReleve',
            campagne__service__pb2.MarquerNonReleveRequest.SerializeToString,
            campagne__service__pb2.ReleveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReleve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/GetReleve',
            campagne__service__pb2.ReleveIdRequest.SerializeToString,
            campagne__service__pb2.ReleveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReleves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/ListReleves',
            campagne__service__pb2.CampagneIdRequest.SerializeToString,
            campagne__service__pb2.ListRelevesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgression(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/GetProgression',
            campagne__service__pb2.CampagneIdRequest.SerializeToString,
            campagne__service__pb2.ProgressionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResumeCloture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/GetResumeCloture',
            campagne__service__pb2.CampagneIdRequest.SerializeToString,
            campagne__service__pb2.ResumeClotureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloturerCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/CloturerCampagne',
            campagne__service__pb2.CampagneIdRequest.SerializeToString,
            campagne__service__pb2.CampagneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDernierIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campagne.CampagneService/GetDernierIndex',
            campagne__service__pb2.AbonneIdRequest.SerializeToString,
            campagne__service__pb2.DernierIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
