# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notification_service_pb2 as notification__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in notification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnvoyerFacture = channel.unary_unary(
                '/notification.NotificationService/EnvoyerFacture',
                request_serializer=notification__service__pb2.EnvoyerFactureRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.ReenvoyerFacture = channel.unary_unary(
                '/notification.NotificationService/ReenvoyerFacture',
                request_serializer=notification__service__pb2.FactureIdRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.EnvoyerRelance = channel.unary_unary(
                '/notification.NotificationService/EnvoyerRelance',
                request_serializer=notification__service__pb2.EnvoyerRelanceRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.GetEnvoi = channel.unary_unary(
                '/notification.NotificationService/GetEnvoi',
                request_serializer=notification__service__pb2.EnvoiIdRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.ListEnvois = channel.unary_unary(
                '/notification.NotificationService/ListEnvois',
                request_serializer=notification__service__pb2.ListEnvoisRequest.SerializeToString,
                response_deserializer=notification__service__pb2.ListEnvoisResponse.FromString,
                _registered_method=True)
        self.ValiderToken = channel.unary_unary(
                '/notification.NotificationService/ValiderToken',
                request_serializer=notification__service__pb2.ValiderTokenRequest.SerializeToString,
                response_deserializer=notification__service__pb2.ValiderTokenResponse.FromString,
                _registered_method=True)
        self.RevoquerToken = channel.unary_unary(
                '/notification.NotificationService/RevoquerToken',
                request_serializer=notification__service__pb2.TokenIdRequest.SerializeToString,
                response_deserializer=notification__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnvoyerFacture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReenvoyerFacture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnvoyerRelance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvoi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvois(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValiderToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevoquerToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnvoyerFacture': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvoyerFacture,
                    request_deserializer=notification__service__pb2.EnvoyerFactureRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'ReenvoyerFacture': grpc.unary_unary_rpc_method_handler(
                    servicer.ReenvoyerFacture,
                    request_deserializer=notification__service__pb2.FactureIdRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'EnvoyerRelance': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvoyerRelance,
                    request_deserializer=notification__service__pb2.EnvoyerRelanceRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'GetEnvoi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvoi,
                    request_deserializer=notification__service__pb2.EnvoiIdRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'ListEnvois': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvois,
                    request_deserializer=notification__service__pb2.ListEnvoisRequest.FromString,
                    response_serializer=notification__service__pb2.ListEnvoisResponse.SerializeToString,
            ),
            'ValiderToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValiderToken,
                    request_deserializer=notification__service__pb2.ValiderTokenRequest.FromString,
                    response_serializer=notification__service__pb2.ValiderTokenResponse.SerializeToString,
            ),
            'RevoquerToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevoquerToken,
                    request_deserializer=notification__service__pb2.TokenIdRequest.FromString,
                    response_serializer=notification__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notification.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnvoyerFacture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/EnvoyerFacture',
            notification__service__pb2.EnvoyerFactureRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReenvoyerFacture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/ReenvoyerFacture',
            notification__service__pb2.FactureIdRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnvoyerRelance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/EnvoyerRelance',
            notification__service__pb2.EnvoyerRelanceRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvoi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/GetEnvoi',
            notification__service__pb2.EnvoiIdRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvois(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/ListEnvois',
            notification__service__pb2.ListEnvoisRequest.SerializeToString,
            notification__service__pb2.ListEnvoisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValiderToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/ValiderToken',
            notification__service__pb2.ValiderTokenRequest.SerializeToString,
            notification__service__pb2.ValiderTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevoquerToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/RevoquerToken',
            notification__service__pb2.TokenIdRequest.SerializeToString,
            notification__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
