# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notification_service_pb2 as notification__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnvoyerFacture = channel.unary_unary(
                '/notification.NotificationService/EnvoyerFacture',
                request_serializer=notification__service__pb2.EnvoyerFactureRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.ReenvoyerFacture = channel.unary_unary(
                '/notification.NotificationService/ReenvoyerFacture',
                request_serializer=notification__service__pb2.FactureIdRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.EnvoyerRecu = channel.unary_unary(
                '/notification.NotificationService/EnvoyerRecu',
                request_serializer=notification__service__pb2.EnvoyerRecuRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.EnvoyerRelance = channel.unary_unary(
                '/notification.NotificationService/EnvoyerRelance',
                request_serializer=notification__service__pb2.EnvoyerRelanceRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.GetEnvoi = channel.unary_unary(
                '/notification.NotificationService/GetEnvoi',
                request_serializer=notification__service__pb2.EnvoiIdRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EnvoiResponse.FromString,
                _registered_method=True)
        self.ListEnvois = channel.unary_unary(
                '/notification.NotificationService/ListEnvois',
                request_serializer=notification__service__pb2.ListEnvoisRequest.SerializeToString,
                response_deserializer=notification__service__pb2.ListEnvoisResponse.FromString,
                _registered_method=True)
        self.ValiderToken = channel.unary_unary(
                '/notification.NotificationService/ValiderToken',
                request_serializer=notification__service__pb2.ValiderTokenRequest.SerializeToString,
                response_deserializer=notification__service__pb2.ValiderTokenResponse.FromString,
                _registered_method=True)
        self.RevoquerToken = channel.unary_unary(
                '/notification.NotificationService/RevoquerToken',
                request_serializer=notification__service__pb2.TokenIdRequest.SerializeToString,
                response_deserializer=notification__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RevoquerTousTokens = channel.unary_unary(
                '/notification.NotificationService/RevoquerTousTokens',
                request_serializer=notification__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=notification__service__pb2.RevoquerTousTokensResponse.FromString,
                _registered_method=True)
        self.GetEspaceUrl = channel.unary_unary(
                '/notification.NotificationService/GetEspaceUrl',
                request_serializer=notification__service__pb2.GetEspaceUrlRequest.SerializeToString,
                response_deserializer=notification__service__pb2.EspaceUrlResponse.FromString,
                _registered_method=True)
        self.NotifierAdmins = channel.unary_unary(
                '/notification.NotificationService/NotifierAdmins',
                request_serializer=notification__service__pb2.NotifierAdminsRequest.SerializeToString,
                response_deserializer=notification__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetWhatsAppQr = channel.unary_unary(
                '/notification.NotificationService/GetWhatsAppQr',
                request_serializer=notification__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=notification__service__pb2.WhatsAppQrResponse.FromString,
                _registered_method=True)
        self.TesterEnvoi = channel.unary_unary(
                '/notification.NotificationService/TesterEnvoi',
                request_serializer=notification__service__pb2.TesterEnvoiRequest.SerializeToString,
                response_deserializer=notification__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EnvoyerFacture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReenvoyerFacture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnvoyerRecu(self, request, context):
        """Confirmation de paiement : envoie le reçu (PDF) à l'abonné après un versement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnvoyerRelance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvoi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvois(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValiderToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevoquerToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevoquerTousTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEspaceUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifierAdmins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWhatsAppQr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TesterEnvoi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnvoyerFacture': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvoyerFacture,
                    request_deserializer=notification__service__pb2.EnvoyerFactureRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'ReenvoyerFacture': grpc.unary_unary_rpc_method_handler(
                    servicer.ReenvoyerFacture,
                    request_deserializer=notification__service__pb2.FactureIdRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'EnvoyerRecu': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvoyerRecu,
                    request_deserializer=notification__service__pb2.EnvoyerRecuRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'EnvoyerRelance': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvoyerRelance,
                    request_deserializer=notification__service__pb2.EnvoyerRelanceRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'GetEnvoi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvoi,
                    request_deserializer=notification__service__pb2.EnvoiIdRequest.FromString,
                    response_serializer=notification__service__pb2.EnvoiResponse.SerializeToString,
            ),
            'ListEnvois': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvois,
                    request_deserializer=notification__service__pb2.ListEnvoisRequest.FromString,
                    response_serializer=notification__service__pb2.ListEnvoisResponse.SerializeToString,
            ),
            'ValiderToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValiderToken,
                    request_deserializer=notification__service__pb2.ValiderTokenRequest.FromString,
                    response_serializer=notification__service__pb2.ValiderTokenResponse.SerializeToString,
            ),
            'RevoquerToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevoquerToken,
                    request_deserializer=notification__service__pb2.TokenIdRequest.FromString,
                    response_serializer=notification__service__pb2.StatusResponse.SerializeToString,
            ),
            'RevoquerTousTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.RevoquerTousTokens,
                    request_deserializer=notification__service__pb2.EmptyRequest.FromString,
                    response_serializer=notification__service__pb2.RevoquerTousTokensResponse.SerializeToString,
            ),
            'GetEspaceUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEspaceUrl,
                    request_deserializer=notification__service__pb2.GetEspaceUrlRequest.FromString,
                    response_serializer=notification__service__pb2.EspaceUrlResponse.SerializeToString,
            ),
            'NotifierAdmins': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifierAdmins,
                    request_deserializer=notification__service__pb2.NotifierAdminsRequest.FromString,
                    response_serializer=notification__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetWhatsAppQr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWhatsAppQr,
                    request_deserializer=notification__service__pb2.EmptyRequest.FromString,
                    response_serializer=notification__service__pb2.WhatsAppQrResponse.SerializeToString,
            ),
            'TesterEnvoi': grpc.unary_unary_rpc_method_handler(
                    servicer.TesterEnvoi,
                    request_deserializer=notification__service__pb2.TesterEnvoiRequest.FromString,
                    response_serializer=notification__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notification.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnvoyerFacture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/EnvoyerFacture',
            notification__service__pb2.EnvoyerFactureRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReenvoyerFacture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/ReenvoyerFacture',
            notification__service__pb2.FactureIdRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnvoyerRecu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/EnvoyerRecu',
            notification__service__pb2.EnvoyerRecuRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnvoyerRelance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/EnvoyerRelance',
            notification__service__pb2.EnvoyerRelanceRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvoi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/GetEnvoi',
            notification__service__pb2.EnvoiIdRequest.SerializeToString,
            notification__service__pb2.EnvoiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvois(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/ListEnvois',
            notification__service__pb2.ListEnvoisRequest.SerializeToString,
            notification__service__pb2.ListEnvoisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValiderToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/ValiderToken',
            notification__service__pb2.ValiderTokenRequest.SerializeToString,
            notification__service__pb2.ValiderTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevoquerToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/RevoquerToken',
            notification__service__pb2.TokenIdRequest.SerializeToString,
            notification__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevoquerTousTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/RevoquerTousTokens',
            notification__service__pb2.EmptyRequest.SerializeToString,
            notification__service__pb2.RevoquerTousTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEspaceUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/GetEspaceUrl',
            notification__service__pb2.GetEspaceUrlRequest.SerializeToString,
            notification__service__pb2.EspaceUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifierAdmins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/NotifierAdmins',
            notification__service__pb2.NotifierAdminsRequest.SerializeToString,
            notification__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWhatsAppQr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/GetWhatsAppQr',
            notification__service__pb2.EmptyRequest.SerializeToString,
            notification__service__pb2.WhatsAppQrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TesterEnvoi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/TesterEnvoi',
            notification__service__pb2.TesterEnvoiRequest.SerializeToString,
            notification__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
