# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import paiement_service_pb2 as paiement__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in paiement_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaiementServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitialiserSolde = channel.unary_unary(
                '/paiement.PaiementService/InitialiserSolde',
                request_serializer=paiement__service__pb2.InitialiserSoldeRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.SoldeResponse.FromString,
                _registered_method=True)
        self.EnregistrerPaiement = channel.unary_unary(
                '/paiement.PaiementService/EnregistrerPaiement',
                request_serializer=paiement__service__pb2.EnregistrerPaiementRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.PaiementResponse.FromString,
                _registered_method=True)
        self.AnnulerPaiement = channel.unary_unary(
                '/paiement.PaiementService/AnnulerPaiement',
                request_serializer=paiement__service__pb2.AnnulerPaiementRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.PaiementResponse.FromString,
                _registered_method=True)
        self.GetSolde = channel.unary_unary(
                '/paiement.PaiementService/GetSolde',
                request_serializer=paiement__service__pb2.FactureIdRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.SoldeResponse.FromString,
                _registered_method=True)
        self.ListPaiements = channel.unary_unary(
                '/paiement.PaiementService/ListPaiements',
                request_serializer=paiement__service__pb2.ListPaiementsRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.ListPaiementsResponse.FromString,
                _registered_method=True)
        self.ListPaiementsParCampagne = channel.unary_unary(
                '/paiement.PaiementService/ListPaiementsParCampagne',
                request_serializer=paiement__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.ListPaiementsResponse.FromString,
                _registered_method=True)
        self.ListImpayes = channel.unary_unary(
                '/paiement.PaiementService/ListImpayes',
                request_serializer=paiement__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.ListImpayesResponse.FromString,
                _registered_method=True)
        self.GetSuiviImpaye = channel.unary_unary(
                '/paiement.PaiementService/GetSuiviImpaye',
                request_serializer=paiement__service__pb2.FactureIdRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.SuiviImpayeResponse.FromString,
                _registered_method=True)
        self.CrediterAvoir = channel.unary_unary(
                '/paiement.PaiementService/CrediterAvoir',
                request_serializer=paiement__service__pb2.CrediterAvoirRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.AvoirResponse.FromString,
                _registered_method=True)
        self.GetAvoirAbonne = channel.unary_unary(
                '/paiement.PaiementService/GetAvoirAbonne',
                request_serializer=paiement__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=paiement__service__pb2.AvoirResponse.FromString,
                _registered_method=True)


class PaiementServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InitialiserSolde(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnregistrerPaiement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnulerPaiement(self, request, context):
        """Annule un paiement enregistré par erreur (rétablit le solde) — avec traçabilité.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSolde(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaiements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaiementsParCampagne(self, request, context):
        """Liste les paiements de toutes les factures d'une campagne (export CSV
        back-office, écran 13). Le rattachement passe par SoldeFacture.campagne_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListImpayes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSuiviImpaye(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrediterAvoir(self, request, context):
        """Avoir (crédit) de l'abonné : émission d'un avoir manuel (rectification) et
        consultation du solde + journal des mouvements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvoirAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaiementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitialiserSolde': grpc.unary_unary_rpc_method_handler(
                    servicer.InitialiserSolde,
                    request_deserializer=paiement__service__pb2.InitialiserSoldeRequest.FromString,
                    response_serializer=paiement__service__pb2.SoldeResponse.SerializeToString,
            ),
            'EnregistrerPaiement': grpc.unary_unary_rpc_method_handler(
                    servicer.EnregistrerPaiement,
                    request_deserializer=paiement__service__pb2.EnregistrerPaiementRequest.FromString,
                    response_serializer=paiement__service__pb2.PaiementResponse.SerializeToString,
            ),
            'AnnulerPaiement': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnulerPaiement,
                    request_deserializer=paiement__service__pb2.AnnulerPaiementRequest.FromString,
                    response_serializer=paiement__service__pb2.PaiementResponse.SerializeToString,
            ),
            'GetSolde': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSolde,
                    request_deserializer=paiement__service__pb2.FactureIdRequest.FromString,
                    response_serializer=paiement__service__pb2.SoldeResponse.SerializeToString,
            ),
            'ListPaiements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaiements,
                    request_deserializer=paiement__service__pb2.ListPaiementsRequest.FromString,
                    response_serializer=paiement__service__pb2.ListPaiementsResponse.SerializeToString,
            ),
            'ListPaiementsParCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaiementsParCampagne,
                    request_deserializer=paiement__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=paiement__service__pb2.ListPaiementsResponse.SerializeToString,
            ),
            'ListImpayes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListImpayes,
                    request_deserializer=paiement__service__pb2.EmptyRequest.FromString,
                    response_serializer=paiement__service__pb2.ListImpayesResponse.SerializeToString,
            ),
            'GetSuiviImpaye': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuiviImpaye,
                    request_deserializer=paiement__service__pb2.FactureIdRequest.FromString,
                    response_serializer=paiement__service__pb2.SuiviImpayeResponse.SerializeToString,
            ),
            'CrediterAvoir': grpc.unary_unary_rpc_method_handler(
                    servicer.CrediterAvoir,
                    request_deserializer=paiement__service__pb2.CrediterAvoirRequest.FromString,
                    response_serializer=paiement__service__pb2.AvoirResponse.SerializeToString,
            ),
            'GetAvoirAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvoirAbonne,
                    request_deserializer=paiement__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=paiement__service__pb2.AvoirResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paiement.PaiementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paiement.PaiementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaiementService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitialiserSolde(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/InitialiserSolde',
            paiement__service__pb2.InitialiserSoldeRequest.SerializeToString,
            paiement__service__pb2.SoldeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnregistrerPaiement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/EnregistrerPaiement',
            paiement__service__pb2.EnregistrerPaiementRequest.SerializeToString,
            paiement__service__pb2.PaiementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnulerPaiement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/AnnulerPaiement',
            paiement__service__pb2.AnnulerPaiementRequest.SerializeToString,
            paiement__service__pb2.PaiementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSolde(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/GetSolde',
            paiement__service__pb2.FactureIdRequest.SerializeToString,
            paiement__service__pb2.SoldeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaiements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/ListPaiements',
            paiement__service__pb2.ListPaiementsRequest.SerializeToString,
            paiement__service__pb2.ListPaiementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaiementsParCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/ListPaiementsParCampagne',
            paiement__service__pb2.CampagneIdRequest.SerializeToString,
            paiement__service__pb2.ListPaiementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListImpayes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/ListImpayes',
            paiement__service__pb2.EmptyRequest.SerializeToString,
            paiement__service__pb2.ListImpayesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSuiviImpaye(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/GetSuiviImpaye',
            paiement__service__pb2.FactureIdRequest.SerializeToString,
            paiement__service__pb2.SuiviImpayeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrediterAvoir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/CrediterAvoir',
            paiement__service__pb2.CrediterAvoirRequest.SerializeToString,
            paiement__service__pb2.AvoirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvoirAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paiement.PaiementService/GetAvoirAbonne',
            paiement__service__pb2.AbonneIdRequest.SerializeToString,
            paiement__service__pb2.AvoirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
