# Generated by Django 5.2.15 on 2026-07-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsCampagne',
            fields=[
                ('campagne_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nom_campagne', models.CharField(default='', max_length=100)),
                ('total_abonnes', models.IntegerField(default=0)),
                ('nb_releves', models.IntegerField(default=0)),
                ('nb_en_attente', models.IntegerField(default=0)),
                ('nb_estimes', models.IntegerField(default=0)),
                ('nb_non_releves', models.IntegerField(default=0)),
                ('pourcentage_progression', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consommation_totale', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_campagnes',
            },
        ),
        migrations.CreateModel(
            name='StatsFacturation',
            fields=[
                ('campagne_id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_factures', models.IntegerField(default=0)),
                ('montant_total_facture', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_factures_envoyees', models.IntegerField(default=0)),
                ('nb_factures_payees', models.IntegerField(default=0)),
                ('nb_factures_partielles', models.IntegerField(default=0)),
                ('nb_factures_impayees', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_facturation',
            },
        ),
        migrations.CreateModel(
            name='StatsPaiements',
            fields=[
                ('campagne_id', models.UUIDField(primary_key=True, serialize=False)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_impaye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_impayes', models.IntegerField(default=0)),
                ('taux_recouvrement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_paiements',
            },
        ),
    ]
