# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reporting_service_pb2 as reporting__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reporting_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDashboard = channel.unary_unary(
                '/reporting.ReportingService/GetDashboard',
                request_serializer=reporting__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=reporting__service__pb2.DashboardResponse.FromString,
                _registered_method=True)
        self.GetStatsCampagne = channel.unary_unary(
                '/reporting.ReportingService/GetStatsCampagne',
                request_serializer=reporting__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=reporting__service__pb2.StatsCampagneResponse.FromString,
                _registered_method=True)
        self.GetStatsGlobales = channel.unary_unary(
                '/reporting.ReportingService/GetStatsGlobales',
                request_serializer=reporting__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=reporting__service__pb2.StatsGlobalesResponse.FromString,
                _registered_method=True)
        self.UpdateStatsCampagne = channel.unary_unary(
                '/reporting.ReportingService/UpdateStatsCampagne',
                request_serializer=reporting__service__pb2.UpdateStatsCampagneRequest.SerializeToString,
                response_deserializer=reporting__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateStatsFacturation = channel.unary_unary(
                '/reporting.ReportingService/UpdateStatsFacturation',
                request_serializer=reporting__service__pb2.UpdateStatsFacturationRequest.SerializeToString,
                response_deserializer=reporting__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateStatsPaiements = channel.unary_unary(
                '/reporting.ReportingService/UpdateStatsPaiements',
                request_serializer=reporting__service__pb2.UpdateStatsPaiementsRequest.SerializeToString,
                response_deserializer=reporting__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class ReportingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsCampagne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsGlobales(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatsCampagne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatsFacturation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatsPaiements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboard,
                    request_deserializer=reporting__service__pb2.EmptyRequest.FromString,
                    response_serializer=reporting__service__pb2.DashboardResponse.SerializeToString,
            ),
            'GetStatsCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsCampagne,
                    request_deserializer=reporting__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=reporting__service__pb2.StatsCampagneResponse.SerializeToString,
            ),
            'GetStatsGlobales': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsGlobales,
                    request_deserializer=reporting__service__pb2.EmptyRequest.FromString,
                    response_serializer=reporting__service__pb2.StatsGlobalesResponse.SerializeToString,
            ),
            'UpdateStatsCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatsCampagne,
                    request_deserializer=reporting__service__pb2.UpdateStatsCampagneRequest.FromString,
                    response_serializer=reporting__service__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateStatsFacturation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatsFacturation,
                    request_deserializer=reporting__service__pb2.UpdateStatsFacturationRequest.FromString,
                    response_serializer=reporting__service__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateStatsPaiements': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatsPaiements,
                    request_deserializer=reporting__service__pb2.UpdateStatsPaiementsRequest.FromString,
                    response_serializer=reporting__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reporting.ReportingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reporting.ReportingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reporting.ReportingService/GetDashboard',
            reporting__service__pb2.EmptyRequest.SerializeToString,
            reporting__service__pb2.DashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reporting.ReportingService/GetStatsCampagne',
            reporting__service__pb2.CampagneIdRequest.SerializeToString,
            reporting__service__pb2.StatsCampagneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsGlobales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reporting.ReportingService/GetStatsGlobales',
            reporting__service__pb2.EmptyRequest.SerializeToString,
            reporting__service__pb2.StatsGlobalesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatsCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reporting.ReportingService/UpdateStatsCampagne',
            reporting__service__pb2.UpdateStatsCampagneRequest.SerializeToString,
            reporting__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatsFacturation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reporting.ReportingService/UpdateStatsFacturation',
            reporting__service__pb2.UpdateStatsFacturationRequest.SerializeToString,
            reporting__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatsPaiements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reporting.ReportingService/UpdateStatsPaiements',
            reporting__service__pb2.UpdateStatsPaiementsRequest.SerializeToString,
            reporting__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
