# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import abonne_service_pb2 as abonne__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in abonne_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AbonneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAbonne = channel.unary_unary(
                '/abonne.AbonneService/GetAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ListAbonnes = channel.unary_unary(
                '/abonne.AbonneService/ListAbonnes',
                request_serializer=abonne__service__pb2.ListAbonnesRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListAbonnesResponse.FromString,
                _registered_method=True)
        self.ListAbonnesActifs = channel.unary_unary(
                '/abonne.AbonneService/ListAbonnesActifs',
                request_serializer=abonne__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListAbonnesResponse.FromString,
                _registered_method=True)
        self.CreateAbonne = channel.unary_unary(
                '/abonne.AbonneService/CreateAbonne',
                request_serializer=abonne__service__pb2.CreateAbonneRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.UpdateAbonne = channel.unary_unary(
                '/abonne.AbonneService/UpdateAbonne',
                request_serializer=abonne__service__pb2.UpdateAbonneRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.SuspendreAbonne = channel.unary_unary(
                '/abonne.AbonneService/SuspendreAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ReactiverAbonne = channel.unary_unary(
                '/abonne.AbonneService/ReactiverAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ResilierAbonne = channel.unary_unary(
                '/abonne.AbonneService/ResilierAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.GetCompteur = channel.unary_unary(
                '/abonne.AbonneService/GetCompteur',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.CompteurResponse.FromString,
                _registered_method=True)
        self.UpdateCompteur = channel.unary_unary(
                '/abonne.AbonneService/UpdateCompteur',
                request_serializer=abonne__service__pb2.UpdateCompteurRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.CompteurResponse.FromString,
                _registered_method=True)
        self.RemplacerCompteur = channel.unary_unary(
                '/abonne.AbonneService/RemplacerCompteur',
                request_serializer=abonne__service__pb2.RemplacerCompteurRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.CompteurResponse.FromString,
                _registered_method=True)
        self.GetHistoriqueCompteur = channel.unary_unary(
                '/abonne.AbonneService/GetHistoriqueCompteur',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListHistoriqueResponse.FromString,
                _registered_method=True)


class AbonneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAbonnes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAbonnesActifs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendreAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReactiverAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResilierAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemplacerCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoriqueCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AbonneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ListAbonnes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAbonnes,
                    request_deserializer=abonne__service__pb2.ListAbonnesRequest.FromString,
                    response_serializer=abonne__service__pb2.ListAbonnesResponse.SerializeToString,
            ),
            'ListAbonnesActifs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAbonnesActifs,
                    request_deserializer=abonne__service__pb2.EmptyRequest.FromString,
                    response_serializer=abonne__service__pb2.ListAbonnesResponse.SerializeToString,
            ),
            'CreateAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAbonne,
                    request_deserializer=abonne__service__pb2.CreateAbonneRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'UpdateAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAbonne,
                    request_deserializer=abonne__service__pb2.UpdateAbonneRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'SuspendreAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendreAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ReactiverAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.ReactiverAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ResilierAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.ResilierAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'GetCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompteur,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.CompteurResponse.SerializeToString,
            ),
            'UpdateCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCompteur,
                    request_deserializer=abonne__service__pb2.UpdateCompteurRequest.FromString,
                    response_serializer=abonne__service__pb2.CompteurResponse.SerializeToString,
            ),
            'RemplacerCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.RemplacerCompteur,
                    request_deserializer=abonne__service__pb2.RemplacerCompteurRequest.FromString,
                    response_serializer=abonne__service__pb2.CompteurResponse.SerializeToString,
            ),
            'GetHistoriqueCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoriqueCompteur,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.ListHistoriqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'abonne.AbonneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('abonne.AbonneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AbonneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/GetAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAbonnes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ListAbonnes',
            abonne__service__pb2.ListAbonnesRequest.SerializeToString,
            abonne__service__pb2.ListAbonnesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAbonnesActifs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ListAbonnesActifs',
            abonne__service__pb2.EmptyRequest.SerializeToString,
            abonne__service__pb2.ListAbonnesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/CreateAbonne',
            abonne__service__pb2.CreateAbonneRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/UpdateAbonne',
            abonne__service__pb2.UpdateAbonneRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendreAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/SuspendreAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReactiverAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ReactiverAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResilierAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ResilierAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/GetCompteur',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.CompteurResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/UpdateCompteur',
            abonne__service__pb2.UpdateCompteurRequest.SerializeToString,
            abonne__service__pb2.CompteurResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemplacerCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/RemplacerCompteur',
            abonne__service__pb2.RemplacerCompteurRequest.SerializeToString,
            abonne__service__pb2.CompteurResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoriqueCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/GetHistoriqueCompteur',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.ListHistoriqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
