# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import abonne_service_pb2 as abonne__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in abonne_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AbonneServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAbonne = channel.unary_unary(
                '/abonne.AbonneService/GetAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ListAbonnes = channel.unary_unary(
                '/abonne.AbonneService/ListAbonnes',
                request_serializer=abonne__service__pb2.ListAbonnesRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListAbonnesResponse.FromString,
                _registered_method=True)
        self.ListAbonnesActifs = channel.unary_unary(
                '/abonne.AbonneService/ListAbonnesActifs',
                request_serializer=abonne__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListAbonnesResponse.FromString,
                _registered_method=True)
        self.CreateAbonne = channel.unary_unary(
                '/abonne.AbonneService/CreateAbonne',
                request_serializer=abonne__service__pb2.CreateAbonneRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.UpdateAbonne = channel.unary_unary(
                '/abonne.AbonneService/UpdateAbonne',
                request_serializer=abonne__service__pb2.UpdateAbonneRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.SuspendreAbonne = channel.unary_unary(
                '/abonne.AbonneService/SuspendreAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ReactiverAbonne = channel.unary_unary(
                '/abonne.AbonneService/ReactiverAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ResilierAbonne = channel.unary_unary(
                '/abonne.AbonneService/ResilierAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.AnonymiserAbonne = channel.unary_unary(
                '/abonne.AbonneService/AnonymiserAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.AbonneResponse.FromString,
                _registered_method=True)
        self.ExporterDonneesAbonne = channel.unary_unary(
                '/abonne.AbonneService/ExporterDonneesAbonne',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ExportDonneesAbonneResponse.FromString,
                _registered_method=True)
        self.GetCompteur = channel.unary_unary(
                '/abonne.AbonneService/GetCompteur',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.CompteurResponse.FromString,
                _registered_method=True)
        self.UpdateCompteur = channel.unary_unary(
                '/abonne.AbonneService/UpdateCompteur',
                request_serializer=abonne__service__pb2.UpdateCompteurRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.CompteurResponse.FromString,
                _registered_method=True)
        self.RemplacerCompteur = channel.unary_unary(
                '/abonne.AbonneService/RemplacerCompteur',
                request_serializer=abonne__service__pb2.RemplacerCompteurRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.CompteurResponse.FromString,
                _registered_method=True)
        self.GetHistoriqueCompteur = channel.unary_unary(
                '/abonne.AbonneService/GetHistoriqueCompteur',
                request_serializer=abonne__service__pb2.AbonneIdRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListHistoriqueResponse.FromString,
                _registered_method=True)
        self.ListZones = channel.unary_unary(
                '/abonne.AbonneService/ListZones',
                request_serializer=abonne__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=abonne__service__pb2.ListZonesResponse.FromString,
                _registered_method=True)


class AbonneServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAbonnes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAbonnesActifs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendreAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReactiverAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResilierAbonne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnonymiserAbonne(self, request, context):
        """RGPD — droit à l'effacement. N'anonymise QUE l'identité nominative côté
        Abonné Service (nom, prénom, téléphone WhatsApp, adresse) ; refuse si
        l'abonné n'est pas déjà RESILIE. Ne touche à aucune autre donnée
        (compteur, historique, factures/paiements — hors périmètre de ce
        service). Idempotent : ré-appeler sur un abonné déjà anonymisé
        réapplique les mêmes valeurs sans erreur.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExporterDonneesAbonne(self, request, context):
        """RGPD — droit à la portabilité. Agrège, pour un abonné, ses données
        propres (déchiffrées) et celles des autres services (compteurs,
        relevés, factures, paiements, envois WhatsApp) via gRPC, en un export
        JSON structuré. Dégradation gracieuse par section : un service
        injoignable ne fait pas échouer l'export dans son ensemble, sa section
        documente juste l'indisponibilité (voir abonnes/export.py).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemplacerCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoriqueCompteur(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListZones(self, request, context):
        """Zones de relevé distinctes (quartier + camp) avec le nombre d'abonnés
        actifs — sert à l'affectation des agents par zone (Campagne/Gateway).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AbonneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ListAbonnes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAbonnes,
                    request_deserializer=abonne__service__pb2.ListAbonnesRequest.FromString,
                    response_serializer=abonne__service__pb2.ListAbonnesResponse.SerializeToString,
            ),
            'ListAbonnesActifs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAbonnesActifs,
                    request_deserializer=abonne__service__pb2.EmptyRequest.FromString,
                    response_serializer=abonne__service__pb2.ListAbonnesResponse.SerializeToString,
            ),
            'CreateAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAbonne,
                    request_deserializer=abonne__service__pb2.CreateAbonneRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'UpdateAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAbonne,
                    request_deserializer=abonne__service__pb2.UpdateAbonneRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'SuspendreAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendreAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ReactiverAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.ReactiverAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ResilierAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.ResilierAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'AnonymiserAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.AnonymiserAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.AbonneResponse.SerializeToString,
            ),
            'ExporterDonneesAbonne': grpc.unary_unary_rpc_method_handler(
                    servicer.ExporterDonneesAbonne,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.ExportDonneesAbonneResponse.SerializeToString,
            ),
            'GetCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompteur,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.CompteurResponse.SerializeToString,
            ),
            'UpdateCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCompteur,
                    request_deserializer=abonne__service__pb2.UpdateCompteurRequest.FromString,
                    response_serializer=abonne__service__pb2.CompteurResponse.SerializeToString,
            ),
            'RemplacerCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.RemplacerCompteur,
                    request_deserializer=abonne__service__pb2.RemplacerCompteurRequest.FromString,
                    response_serializer=abonne__service__pb2.CompteurResponse.SerializeToString,
            ),
            'GetHistoriqueCompteur': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoriqueCompteur,
                    request_deserializer=abonne__service__pb2.AbonneIdRequest.FromString,
                    response_serializer=abonne__service__pb2.ListHistoriqueResponse.SerializeToString,
            ),
            'ListZones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListZones,
                    request_deserializer=abonne__service__pb2.EmptyRequest.FromString,
                    response_serializer=abonne__service__pb2.ListZonesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'abonne.AbonneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('abonne.AbonneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AbonneService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/GetAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAbonnes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ListAbonnes',
            abonne__service__pb2.ListAbonnesRequest.SerializeToString,
            abonne__service__pb2.ListAbonnesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAbonnesActifs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ListAbonnesActifs',
            abonne__service__pb2.EmptyRequest.SerializeToString,
            abonne__service__pb2.ListAbonnesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/CreateAbonne',
            abonne__service__pb2.CreateAbonneRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/UpdateAbonne',
            abonne__service__pb2.UpdateAbonneRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendreAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/SuspendreAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReactiverAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ReactiverAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResilierAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ResilierAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnonymiserAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/AnonymiserAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.AbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExporterDonneesAbonne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ExporterDonneesAbonne',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.ExportDonneesAbonneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/GetCompteur',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.CompteurResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/UpdateCompteur',
            abonne__service__pb2.UpdateCompteurRequest.SerializeToString,
            abonne__service__pb2.CompteurResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemplacerCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/RemplacerCompteur',
            abonne__service__pb2.RemplacerCompteurRequest.SerializeToString,
            abonne__service__pb2.CompteurResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoriqueCompteur(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/GetHistoriqueCompteur',
            abonne__service__pb2.AbonneIdRequest.SerializeToString,
            abonne__service__pb2.ListHistoriqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListZones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/abonne.AbonneService/ListZones',
            abonne__service__pb2.EmptyRequest.SerializeToString,
            abonne__service__pb2.ListZonesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
