# Generated by Django 5.2.15 on 2026-06-28 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_abonne', models.CharField(editable=False, max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone_whatsapp', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'abonnes',
                'indexes': [models.Index(fields=['statut'], name='abonnes_statut_f5dc12_idx')],
            },
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_compteur', models.IntegerField()),
                ('quartier', models.CharField(max_length=100)),
                ('camp', models.IntegerField()),
                ('index_initial', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('date_pose', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('REMPLACE', 'Remplacé'), ('DESACTIVE', 'Désactivé')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='abonnes.abonne')),
            ],
            options={
                'db_table': 'compteurs',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCompteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_fermeture', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_remplacement', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_compteurs', to='abonnes.abonne')),
                ('ancien_compteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='abonnes.compteur')),
                ('nouveau_compteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='abonnes.compteur')),
            ],
            options={
                'db_table': 'historique_compteurs',
            },
        ),
        migrations.AddIndex(
            model_name='compteur',
            index=models.Index(fields=['abonne'], name='compteurs_abonne__3a7622_idx'),
        ),
    ]
