# Generated by Django 5.2.15 on 2026-06-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abonnes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compteur",
            name="numero_compteur",
            field=models.IntegerField(unique=True),
        ),
    ]
