# Generated by Django 5.2.15 on 2026-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0002_alter_compteur_numero_compteur'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compteur',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('abonne',), name='unique_compteur_actif_par_abonne'),
        ),
    ]
