# Generated by Django 5.2.15 on 2026-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0003_compteur_unique_compteur_actif_par_abonne'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquecompteur',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
