# Generated by Django 5.2.15 on 2026-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0004_historiquecompteur_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
