# Generated by Django 5.2.15 on 2026-09-03 12:33
#
# Migration de SCHÉMA uniquement : bascule nom/prenom/telephone_whatsapp/
# adresse vers les champs chiffrés (abonnes/fields.py) et élargit la colonne
# des trois premiers en TEXT (un token Fernet dépasse largement VARCHAR(100)/
# VARCHAR(20) — voir EncryptedCharField.db_type). Elle NE rechiffre PAS les
# lignes existantes : c'est le rôle de la migration de données suivante
# (0007_encrypt_existing_pii_data), qui doit impérativement s'exécuter APRÈS
# celle-ci (colonnes déjà élargies) mais raisonne en SQL brut pour ne pas
# passer par ces mêmes champs déjà « chiffrants » à cette étape.

import abonnes.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0005_compteur_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='adresse',
            field=abonnes.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='nom',
            field=abonnes.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='prenom',
            field=abonnes.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='telephone_whatsapp',
            field=abonnes.fields.EncryptedCharField(max_length=20),
        ),
    ]
