# Generated by Django 5.2.17 on 2026-09-05 01:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0008_rotate_pii_encryption_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.CharField(max_length=100)),
                ('acteur_id', models.CharField(blank=True, default='', max_length=100)),
                ('acteur_nom', models.CharField(blank=True, default='', max_length=150)),
                ('acteur_role', models.CharField(blank=True, default='', max_length=50)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['objet_type', 'objet_id'], name='audit_log_objet_t_b6da20_idx'), models.Index(fields=['horodatage'], name='audit_log_horodat_563282_idx')],
            },
        ),
    ]
