# Generated by Django 5.2.17 on 2026-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0011_audit_log_role_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='date_maj_position',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteur',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='compteur',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
