# Generated by Django 5.2.15 on 2026-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_facture_c032a3_idx',
            old_name='paiements_facture_id_idx',
        ),
        migrations.AddField(
            model_name='soldefacture',
            name='campagne_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
