# Generated by Django 5.2.16 on 2026-08-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0006_mouvementavoir'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mouvementavoir',
            new_name='mouvements__abonne__193610_idx',
            old_name='mouvements__abonne__idx',
        ),
        migrations.AlterField(
            model_name='mouvementavoir',
            name='type_mouvement',
            field=models.CharField(choices=[('TROP_PERCU', 'Trop-perçu'), ('RECTIFICATION', 'Rectification'), ('IMPUTATION', 'Imputation'), ('ANNULATION', 'Annulation de facture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('AVOIR', 'Avoir (report de trop-perçu)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='soldefacture',
            name='statut',
            field=models.CharField(choices=[('IMPAYEE', 'Impayée'), ('PARTIELLE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='IMPAYEE', max_length=10),
        ),
    ]
