# Generated by Django 5.2.16 on 2026-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiements", "0007_rename_mouvements__abonne__idx_mouvements__abonne__193610_idx_and_more"),
    ]

    operations = [
        # Part d'un versement partie à l'avoir de l'abonné. Défaut zéro : les
        # paiements existants s'étaient imputés entièrement, ou bien leur
        # excédent est déjà consommé — dans les deux cas, leur annulation ne doit
        # rien reprendre à l'avoir.
        migrations.AddField(
            model_name="paiement",
            name="montant_excedent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="mouvementavoir",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("TROP_PERCU", "Trop-perçu"),
                    ("RECTIFICATION", "Rectification"),
                    ("IMPUTATION", "Imputation"),
                    ("ANNULATION", "Annulation de facture"),
                    ("REPRISE_TROP_PERCU", "Reprise d'un trop-perçu annulé"),
                ],
                max_length=20,
            ),
        ),
    ]
