# Generated by Django 5.2.16 on 2026-08-31 19:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiements", "0008_paiement_montant_excedent_and_more"),
    ]

    operations = [
        # Regroupe les écritures d'un même versement.
        #
        # ⚠️ `default=uuid.uuid4` n'est évalué **qu'une fois** par cette
        # migration : toutes les lignes existantes reçoivent la MÊME valeur.
        # C'est la migration 0010 qui leur en donne une chacune — sans elle,
        # annuler un paiement antérieur en annulerait tous les autres.
        migrations.AddField(
            model_name="paiement",
            name="versement_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(fields=["versement_id"], name="paiements_verseme_c01c55_idx"),
        ),
    ]
