# Generated by Django 5.2.16 on 2026-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0010_versement_id_distinct_par_paiement_existant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soldefacture',
            index=models.Index(fields=['abonne_id'], name='soldes_fact_abonne__a96fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='soldefacture',
            index=models.Index(fields=['date_limite_paiement'], name='soldes_fact_date_li_a3fb7f_idx'),
        ),
    ]
