# Generated by Django 5.2.17 on 2026-09-04 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0011_soldefacture_soldes_fact_abonne__a96fd4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPaiementEnLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facture_id', models.CharField(max_length=36)),
                ('abonne_id', models.CharField(max_length=36)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ECHOUEE', 'Échouée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=10)),
                ('token_espace', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_a', models.DateTimeField()),
            ],
            options={
                'db_table': 'sessions_paiement_en_ligne',
                'indexes': [models.Index(fields=['abonne_id'], name='sessions_pa_abonne__1ec2cf_idx')],
            },
        ),
    ]
