# Generated by Django 5.2.15 on 2026-07-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0002_campagneagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='numero_mobile_money',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
