# Generated by Django 5.2.15 on 2026-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0003_campagne_numero_mobile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='envoyer_whatsapp_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campagne',
            name='generer_factures_auto',
            field=models.BooleanField(default=True),
        ),
    ]
