# Generated by Django 5.2.15 on 2026-07-05 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0004_campagne_toggles_cloture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SAISIE', 'Saisie'), ('CORRECTION', 'Correction')], max_length=20)),
                ('auteur_id', models.CharField(max_length=36)),
                ('auteur_username', models.CharField(blank=True, default='', max_length=150)),
                ('auteur_role', models.CharField(blank=True, default='', max_length=20)),
                ('ancien_index', models.FloatField(blank=True, null=True)),
                ('nouvel_index', models.FloatField(blank=True, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='campagnes.releve')),
            ],
            options={
                'db_table': 'releve_audits',
                'ordering': ['horodatage'],
                'indexes': [models.Index(fields=['releve'], name='releve_audi_releve__bad70c_idx')],
            },
        ),
    ]
