# Generated by Django 5.2.15 on 2026-07-05 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0005_releveaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='camp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releve',
            name='quartier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AffectationZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=36)),
                ('quartier', models.CharField(max_length=100)),
                ('camp', models.IntegerField()),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_affectees', to='campagnes.campagne')),
            ],
            options={
                'db_table': 'affectation_zones',
                'indexes': [models.Index(fields=['campagne', 'agent_id'], name='affectation_campagn_cccafe_idx')],
                'unique_together': {('campagne', 'quartier', 'camp')},
            },
        ),
    ]
