# Generated by Django 5.2.15 on 2026-09-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0006_releve_camp_releve_quartier_affectationzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releve',
            name='ancien_index',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='releve',
            name='consommation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='releve',
            name='nouveau_index',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='releveaudit',
            name='ancien_index',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='releveaudit',
            name='nouvel_index',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
