# Generated by Django 5.2.15 on 2026-09-03 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0006_releve_camp_releve_quartier_affectationzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='facturation_en_attente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RegenerationFactureEnAttente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abonne_id', models.CharField(max_length=36)),
                ('motif', models.CharField(max_length=255)),
                ('demande_par', models.CharField(blank=True, default='', max_length=36)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_tentative', models.DateTimeField(blank=True, null=True)),
                ('nb_tentatives', models.PositiveIntegerField(default=0)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regenerations_facture_en_attente', to='campagnes.campagne')),
            ],
            options={
                'db_table': 'regenerations_facture_en_attente',
                'unique_together': {('campagne', 'abonne_id')},
            },
        ),
    ]
