# Generated by Django 5.2.17 on 2026-09-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0007_alter_releve_ancien_index_alter_releve_consommation_and_more'),
        ('campagnes', '0007_campagne_facturation_en_attente_and_more'),
    ]

    operations = [
    ]
