# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import config_service_pb2 as config__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in config_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfosSociete = channel.unary_unary(
                '/config.ConfigService/GetInfosSociete',
                request_serializer=config__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=config__service__pb2.InfosSocieteResponse.FromString,
                _registered_method=True)
        self.UpdateInfosSociete = channel.unary_unary(
                '/config.ConfigService/UpdateInfosSociete',
                request_serializer=config__service__pb2.UpdateInfosRequest.SerializeToString,
                response_deserializer=config__service__pb2.InfosSocieteResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/config.ConfigService/GetConfig',
                request_serializer=config__service__pb2.ConfigKeyRequest.SerializeToString,
                response_deserializer=config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/config.ConfigService/UpdateConfig',
                request_serializer=config__service__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.ListConfigs = channel.unary_unary(
                '/config.ConfigService/ListConfigs',
                request_serializer=config__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=config__service__pb2.ListConfigsResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfosSociete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInfosSociete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfosSociete': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfosSociete,
                    request_deserializer=config__service__pb2.EmptyRequest.FromString,
                    response_serializer=config__service__pb2.InfosSocieteResponse.SerializeToString,
            ),
            'UpdateInfosSociete': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInfosSociete,
                    request_deserializer=config__service__pb2.UpdateInfosRequest.FromString,
                    response_serializer=config__service__pb2.InfosSocieteResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=config__service__pb2.ConfigKeyRequest.FromString,
                    response_serializer=config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=config__service__pb2.UpdateConfigRequest.FromString,
                    response_serializer=config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'ListConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConfigs,
                    request_deserializer=config__service__pb2.EmptyRequest.FromString,
                    response_serializer=config__service__pb2.ListConfigsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfosSociete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigService/GetInfosSociete',
            config__service__pb2.EmptyRequest.SerializeToString,
            config__service__pb2.InfosSocieteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInfosSociete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigService/UpdateInfosSociete',
            config__service__pb2.UpdateInfosRequest.SerializeToString,
            config__service__pb2.InfosSocieteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigService/GetConfig',
            config__service__pb2.ConfigKeyRequest.SerializeToString,
            config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigService/UpdateConfig',
            config__service__pb2.UpdateConfigRequest.SerializeToString,
            config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigService/ListConfigs',
            config__service__pb2.EmptyRequest.SerializeToString,
            config__service__pb2.ListConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
