# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import facturation_service_pb2 as facturation__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in facturation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FacturationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenererFactures = channel.unary_unary(
                '/facturation.FacturationService/GenererFactures',
                request_serializer=facturation__service__pb2.GenererFacturesRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.GenererFacturesResponse.FromString,
                _registered_method=True)
        self.CreerRegularisation = channel.unary_unary(
                '/facturation.FacturationService/CreerRegularisation',
                request_serializer=facturation__service__pb2.CreerRegularisationRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.FactureResponse.FromString,
                _registered_method=True)
        self.GetFacture = channel.unary_unary(
                '/facturation.FacturationService/GetFacture',
                request_serializer=facturation__service__pb2.FactureIdRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.FactureResponse.FromString,
                _registered_method=True)
        self.ListFactures = channel.unary_unary(
                '/facturation.FacturationService/ListFactures',
                request_serializer=facturation__service__pb2.ListFacturesRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.ListFacturesResponse.FromString,
                _registered_method=True)
        self.GetFacturePDF = channel.unary_unary(
                '/facturation.FacturationService/GetFacturePDF',
                request_serializer=facturation__service__pb2.FactureIdRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.PDFResponse.FromString,
                _registered_method=True)
        self.GenererBilanImpayesPDF = channel.unary_unary(
                '/facturation.FacturationService/GenererBilanImpayesPDF',
                request_serializer=facturation__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.PDFResponse.FromString,
                _registered_method=True)
        self.GenererSyntheseCampagnePDF = channel.unary_unary(
                '/facturation.FacturationService/GenererSyntheseCampagnePDF',
                request_serializer=facturation__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.PDFResponse.FromString,
                _registered_method=True)
        self.GenererRecuPaiementPDF = channel.unary_unary(
                '/facturation.FacturationService/GenererRecuPaiementPDF',
                request_serializer=facturation__service__pb2.GenererRecuRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.PDFResponse.FromString,
                _registered_method=True)
        self.UpdateStatutFacture = channel.unary_unary(
                '/facturation.FacturationService/UpdateStatutFacture',
                request_serializer=facturation__service__pb2.UpdateStatutRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.FactureResponse.FromString,
                _registered_method=True)
        self.GetTarifActuel = channel.unary_unary(
                '/facturation.FacturationService/GetTarifActuel',
                request_serializer=facturation__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.TarifResponse.FromString,
                _registered_method=True)
        self.UpdateTarif = channel.unary_unary(
                '/facturation.FacturationService/UpdateTarif',
                request_serializer=facturation__service__pb2.UpdateTarifRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.TarifResponse.FromString,
                _registered_method=True)
        self.GetFacturesParCampagne = channel.unary_unary(
                '/facturation.FacturationService/GetFacturesParCampagne',
                request_serializer=facturation__service__pb2.CampagneIdRequest.SerializeToString,
                response_deserializer=facturation__service__pb2.ListFacturesResponse.FromString,
                _registered_method=True)


class FacturationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenererFactures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreerRegularisation(self, request, context):
        """Constate à la main une dette antérieure à la mise en service. Série de
        numérotation propre (REG-), sans campagne ni index : son montant est
        déclaré, pas calculé — d'où le motif obligatoire.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFacture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFacturePDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenererBilanImpayesPDF(self, request, context):
        """Bilan des impayés (document A4 agrégé) — back-office ADMIN/COMPTABLE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenererSyntheseCampagnePDF(self, request, context):
        """Synthèse chiffrée d'une campagne (stats 3 domaines via Reporting) — écran 13.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenererRecuPaiementPDF(self, request, context):
        """Reçu d'un versement (document A5) — back-office ADMIN/COMPTABLE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatutFacture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTarifActuel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTarif(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFacturesParCampagne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FacturationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenererFactures': grpc.unary_unary_rpc_method_handler(
                    servicer.GenererFactures,
                    request_deserializer=facturation__service__pb2.GenererFacturesRequest.FromString,
                    response_serializer=facturation__service__pb2.GenererFacturesResponse.SerializeToString,
            ),
            'CreerRegularisation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreerRegularisation,
                    request_deserializer=facturation__service__pb2.CreerRegularisationRequest.FromString,
                    response_serializer=facturation__service__pb2.FactureResponse.SerializeToString,
            ),
            'GetFacture': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFacture,
                    request_deserializer=facturation__service__pb2.FactureIdRequest.FromString,
                    response_serializer=facturation__service__pb2.FactureResponse.SerializeToString,
            ),
            'ListFactures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactures,
                    request_deserializer=facturation__service__pb2.ListFacturesRequest.FromString,
                    response_serializer=facturation__service__pb2.ListFacturesResponse.SerializeToString,
            ),
            'GetFacturePDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFacturePDF,
                    request_deserializer=facturation__service__pb2.FactureIdRequest.FromString,
                    response_serializer=facturation__service__pb2.PDFResponse.SerializeToString,
            ),
            'GenererBilanImpayesPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GenererBilanImpayesPDF,
                    request_deserializer=facturation__service__pb2.EmptyRequest.FromString,
                    response_serializer=facturation__service__pb2.PDFResponse.SerializeToString,
            ),
            'GenererSyntheseCampagnePDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GenererSyntheseCampagnePDF,
                    request_deserializer=facturation__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=facturation__service__pb2.PDFResponse.SerializeToString,
            ),
            'GenererRecuPaiementPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GenererRecuPaiementPDF,
                    request_deserializer=facturation__service__pb2.GenererRecuRequest.FromString,
                    response_serializer=facturation__service__pb2.PDFResponse.SerializeToString,
            ),
            'UpdateStatutFacture': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatutFacture,
                    request_deserializer=facturation__service__pb2.UpdateStatutRequest.FromString,
                    response_serializer=facturation__service__pb2.FactureResponse.SerializeToString,
            ),
            'GetTarifActuel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTarifActuel,
                    request_deserializer=facturation__service__pb2.EmptyRequest.FromString,
                    response_serializer=facturation__service__pb2.TarifResponse.SerializeToString,
            ),
            'UpdateTarif': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTarif,
                    request_deserializer=facturation__service__pb2.UpdateTarifRequest.FromString,
                    response_serializer=facturation__service__pb2.TarifResponse.SerializeToString,
            ),
            'GetFacturesParCampagne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFacturesParCampagne,
                    request_deserializer=facturation__service__pb2.CampagneIdRequest.FromString,
                    response_serializer=facturation__service__pb2.ListFacturesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facturation.FacturationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('facturation.FacturationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FacturationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenererFactures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GenererFactures',
            facturation__service__pb2.GenererFacturesRequest.SerializeToString,
            facturation__service__pb2.GenererFacturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreerRegularisation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/CreerRegularisation',
            facturation__service__pb2.CreerRegularisationRequest.SerializeToString,
            facturation__service__pb2.FactureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFacture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GetFacture',
            facturation__service__pb2.FactureIdRequest.SerializeToString,
            facturation__service__pb2.FactureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/ListFactures',
            facturation__service__pb2.ListFacturesRequest.SerializeToString,
            facturation__service__pb2.ListFacturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFacturePDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GetFacturePDF',
            facturation__service__pb2.FactureIdRequest.SerializeToString,
            facturation__service__pb2.PDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenererBilanImpayesPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GenererBilanImpayesPDF',
            facturation__service__pb2.EmptyRequest.SerializeToString,
            facturation__service__pb2.PDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenererSyntheseCampagnePDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GenererSyntheseCampagnePDF',
            facturation__service__pb2.CampagneIdRequest.SerializeToString,
            facturation__service__pb2.PDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenererRecuPaiementPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GenererRecuPaiementPDF',
            facturation__service__pb2.GenererRecuRequest.SerializeToString,
            facturation__service__pb2.PDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatutFacture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/UpdateStatutFacture',
            facturation__service__pb2.UpdateStatutRequest.SerializeToString,
            facturation__service__pb2.FactureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTarifActuel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GetTarifActuel',
            facturation__service__pb2.EmptyRequest.SerializeToString,
            facturation__service__pb2.TarifResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTarif(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/UpdateTarif',
            facturation__service__pb2.UpdateTarifRequest.SerializeToString,
            facturation__service__pb2.TarifResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFacturesParCampagne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facturation.FacturationService/GetFacturesParCampagne',
            facturation__service__pb2.CampagneIdRequest.SerializeToString,
            facturation__service__pb2.ListFacturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
