# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_service_pb2 as auth__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=auth__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/auth.AuthService/ValidateToken',
                request_serializer=auth__service__pb2.TokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserPayload.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/auth.AuthService/RefreshToken',
                request_serializer=auth__service__pb2.RefreshRequest.SerializeToString,
                response_deserializer=auth__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/auth.AuthService/Logout',
                request_serializer=auth__service__pb2.TokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/auth.AuthService/CreateUser',
                request_serializer=auth__service__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/auth.AuthService/UpdateUser',
                request_serializer=auth__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeactivateUser = channel.unary_unary(
                '/auth.AuthService/DeactivateUser',
                request_serializer=auth__service__pb2.DeactivateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ReactivateUser = channel.unary_unary(
                '/auth.AuthService/ReactivateUser',
                request_serializer=auth__service__pb2.UserIdRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/auth.AuthService/ListUsers',
                request_serializer=auth__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/auth.AuthService/GetUser',
                request_serializer=auth__service__pb2.UserIdRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.RequestPasswordReset = channel.unary_unary(
                '/auth.AuthService/RequestPasswordReset',
                request_serializer=auth__service__pb2.EmailRequest.SerializeToString,
                response_deserializer=auth__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetPasswordWithToken = channel.unary_unary(
                '/auth.AuthService/SetPasswordWithToken',
                request_serializer=auth__service__pb2.SetPasswordRequest.SerializeToString,
                response_deserializer=auth__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ResetUserPassword = channel.unary_unary(
                '/auth.AuthService/ResetUserPassword',
                request_serializer=auth__service__pb2.UserIdRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.RequestPhoneOtp = channel.unary_unary(
                '/auth.AuthService/RequestPhoneOtp',
                request_serializer=auth__service__pb2.PhoneRequest.SerializeToString,
                response_deserializer=auth__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.VerifyOtpAndSetPassword = channel.unary_unary(
                '/auth.AuthService/VerifyOtpAndSetPassword',
                request_serializer=auth__service__pb2.VerifyOtpRequest.SerializeToString,
                response_deserializer=auth__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """identifier accepte un username ou un numéro de téléphone (+237XXXXXXXXX)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReactivateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPasswordReset(self, request, context):
        """Reset mot de passe ADMIN uniquement (lien e-mail)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPasswordWithToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetUserPassword(self, request, context):
        """Renvoi manuel (déclenché par un admin) des identifiants d'accès à un
        utilisateur donné : lien d'activation si le compte est encore en attente,
        sinon lien/OTP de réinitialisation — selon le rôle et l'état du compte.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPhoneOtp(self, request, context):
        """Activation et reset par OTP WhatsApp (tous les rôles)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOtpAndSetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__service__pb2.LoginRequest.FromString,
                    response_serializer=auth__service__pb2.TokenResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=auth__service__pb2.TokenRequest.FromString,
                    response_serializer=auth__service__pb2.UserPayload.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__service__pb2.RefreshRequest.FromString,
                    response_serializer=auth__service__pb2.TokenResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=auth__service__pb2.TokenRequest.FromString,
                    response_serializer=auth__service__pb2.StatusResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=auth__service__pb2.CreateUserRequest.FromString,
                    response_serializer=auth__service__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=auth__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=auth__service__pb2.UserResponse.SerializeToString,
            ),
            'DeactivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateUser,
                    request_deserializer=auth__service__pb2.DeactivateUserRequest.FromString,
                    response_serializer=auth__service__pb2.UserResponse.SerializeToString,
            ),
            'ReactivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ReactivateUser,
                    request_deserializer=auth__service__pb2.UserIdRequest.FromString,
                    response_serializer=auth__service__pb2.UserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=auth__service__pb2.EmptyRequest.FromString,
                    response_serializer=auth__service__pb2.ListUsersResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=auth__service__pb2.UserIdRequest.FromString,
                    response_serializer=auth__service__pb2.UserResponse.SerializeToString,
            ),
            'RequestPasswordReset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPasswordReset,
                    request_deserializer=auth__service__pb2.EmailRequest.FromString,
                    response_serializer=auth__service__pb2.StatusResponse.SerializeToString,
            ),
            'SetPasswordWithToken': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPasswordWithToken,
                    request_deserializer=auth__service__pb2.SetPasswordRequest.FromString,
                    response_serializer=auth__service__pb2.StatusResponse.SerializeToString,
            ),
            'ResetUserPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetUserPassword,
                    request_deserializer=auth__service__pb2.UserIdRequest.FromString,
                    response_serializer=auth__service__pb2.UserResponse.SerializeToString,
            ),
            'RequestPhoneOtp': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPhoneOtp,
                    request_deserializer=auth__service__pb2.PhoneRequest.FromString,
                    response_serializer=auth__service__pb2.StatusResponse.SerializeToString,
            ),
            'VerifyOtpAndSetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOtpAndSetPassword,
                    request_deserializer=auth__service__pb2.VerifyOtpRequest.FromString,
                    response_serializer=auth__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Login',
            auth__service__pb2.LoginRequest.SerializeToString,
            auth__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateToken',
            auth__service__pb2.TokenRequest.SerializeToString,
            auth__service__pb2.UserPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RefreshToken',
            auth__service__pb2.RefreshRequest.SerializeToString,
            auth__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Logout',
            auth__service__pb2.TokenRequest.SerializeToString,
            auth__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateUser',
            auth__service__pb2.CreateUserRequest.SerializeToString,
            auth__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateUser',
            auth__service__pb2.UpdateUserRequest.SerializeToString,
            auth__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeactivateUser',
            auth__service__pb2.DeactivateUserRequest.SerializeToString,
            auth__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReactivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ReactivateUser',
            auth__service__pb2.UserIdRequest.SerializeToString,
            auth__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListUsers',
            auth__service__pb2.EmptyRequest.SerializeToString,
            auth__service__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUser',
            auth__service__pb2.UserIdRequest.SerializeToString,
            auth__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPasswordReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RequestPasswordReset',
            auth__service__pb2.EmailRequest.SerializeToString,
            auth__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPasswordWithToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/SetPasswordWithToken',
            auth__service__pb2.SetPasswordRequest.SerializeToString,
            auth__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetUserPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ResetUserPassword',
            auth__service__pb2.UserIdRequest.SerializeToString,
            auth__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPhoneOtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RequestPhoneOtp',
            auth__service__pb2.PhoneRequest.SerializeToString,
            auth__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOtpAndSetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/VerifyOtpAndSetPassword',
            auth__service__pb2.VerifyOtpRequest.SerializeToString,
            auth__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
