# Generated by Django 5.2.17 on 2026-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='envoi',
            new_name='envois_facture_b429a0_idx',
            old_name='envois_facture_id_idx',
        ),
        migrations.RenameIndex(
            model_name='envoi',
            new_name='envois_abonne__81ff55_idx',
            old_name='envois_abonne_id_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenacces',
            new_name='tokens_acce_token_09fc0c_idx',
            old_name='tokens_acces_token_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenacces',
            new_name='tokens_acce_abonne__a415d3_idx',
            old_name='tokens_acces_abonne_id_idx',
        ),
        migrations.AlterField(
            model_name='envoi',
            name='type_envoi',
            field=models.CharField(choices=[('FACTURE', 'Facture'), ('RELANCE_1', 'Relance étape 1'), ('RELANCE_2', 'Relance étape 2'), ('AVERTISSEMENT', 'Avertissement'), ('SUSPENSION', 'Suspension'), ('RETABLISSEMENT', 'Rétablissement'), ('RECU', 'Reçu'), ('ANNULATION_PAIEMENT', "Annulation d'un paiement")], max_length=30),
        ),
    ]
