# Generated by Django 5.2.15 on 2026-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_envois_facture_id_idx_envois_facture_b429a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoi',
            name='paiement_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
