# Generated by Django 5.2.15 on 2026-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_envoi_paiement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='type_envoi',
            field=models.CharField(choices=[('FACTURE', 'Facture'), ('RELANCE_1', 'Relance étape 1'), ('RELANCE_2', 'Relance étape 2'), ('AVERTISSEMENT', 'Avertissement'), ('SUSPENSION', 'Suspension'), ('RETABLISSEMENT', 'Rétablissement'), ('RECU', 'Reçu'), ('ANNULATION_PAIEMENT', "Annulation d'un paiement"), ('ANNULATION_FACTURE', "Annulation d'une facture")], max_length=30),
        ),
    ]
