# Generated by Django 5.2.15 on 2026-09-03 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_envoi_type_envoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diffusions',
            },
        ),
        migrations.CreateModel(
            name='DiffusionEnvoi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abonne_id', models.CharField(max_length=36)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('erreur', models.TextField(blank=True, default='')),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diffusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='notifications.diffusion')),
            ],
            options={
                'db_table': 'diffusion_envois',
                'indexes': [models.Index(fields=['diffusion', 'statut'], name='diffusion_e_diffusi_ab7aa2_idx'), models.Index(fields=['abonne_id'], name='diffusion_e_abonne__b3c35f_idx')],
            },
        ),
    ]
