# Generated by Django 5.2.17 on 2026-09-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_diffusion_diffusionenvoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoi',
            name='avec_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envoi',
            name='dernier_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='envoi',
            name='pdf_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
