# Generated by Django 5.2.17 on 2026-09-04
#
# Migration de SCHÉMA uniquement : bascule `telephone` (Envoi et
# DiffusionEnvoi) vers le champ chiffré (notifications/fields.py) et élargit
# la colonne en TEXT (un token Fernet dépasse largement VARCHAR(20) — voir
# EncryptedCharField.db_type). Elle NE rechiffre PAS les lignes existantes :
# c'est le rôle de la migration de données suivante
# (0008_encrypt_existing_telephone_data), qui doit impérativement s'exécuter
# APRÈS celle-ci (colonnes déjà élargies) mais raisonne en SQL brut pour ne
# pas passer par ces mêmes champs déjà « chiffrants » à cette étape.

import notifications.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_envoi_avec_pdf_envoi_dernier_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='telephone',
            field=notifications.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diffusionenvoi',
            name='telephone',
            field=notifications.fields.EncryptedCharField(max_length=20),
        ),
    ]
